apiVersion: apps/v1

kind: Deployment

metadata:
  name: ng-deployment
  namespace: dev
  labels:
    app: ng-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-pod

  template:
    metadata:
      name: ng-pod
      labels:
        app: ng-pod

    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: ng-pod
      
      containers:
        - name: ng-container
          image: frontendvm
          resources:
            requests:
              memory: "64Mi"
              cpu: "64m"
            limits:
              memory: "128Mi"
              cpu: "125m"
          command: ["/entrypoint.sh", "dev-gcp.hsc.com"]
          imagePullPolicy: Always
          ports:
            - containerPort: 80
