substitutions:
  _IMAGE: my-angular-app
  _CLOUD_RUN_SERVICE: frontend-service
  _REGION: us-east4
  _RELEASE_NO: v1.0.0
  
options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build image
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - --cache-from
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:latest
      - .

  # Push image
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA

  # Tag as latest
  - name: gcr.io/cloud-builders/gcloud
    id: Tag
    args:
      - container
      - images
      - add-tag
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
      - us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:latest

  # Deploy to Cloud Run 
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
  id: Deploy to Cloud Run
  entrypoint: gcloud
  args:
    - run
    - deploy
    - $_CLOUD_RUN_SERVICE
    - --image=us-east4-docker.pkg.dev/$PROJECT_ID/techgig-cicd/$_IMAGE:$SHORT_SHA
    - --region=$_REGION
    - --platform=managed
    - --ingress=all
    - --allow-unauthenticated
    - --port=80

